# This dockerfile is to build each branch seperately (for dev purposes)
FROM node:14.17.6
# Create Remix user, don't use root!
# RUN yes | adduser --disabled-password remix && mkdir /app
# USER remix

# #Now do remix stuff
# USER remix
WORKDIR /home/remix

COPY ./ ./

RUN yarn --frozen-lockfile && yarn build:production && yarn install --production --ignore-scripts --prefer-offline

EXPOSE 8080
CMD ["yarn", "serve:production"]
